#!/bin/sh

set -e

case "$1" in
    configure)
	# Remove masks created by dh_systemd_enable on package removal.
	deb-systemd-helper unmask pve-firewall.service >/dev/null || true
	systemctl reload-or-restart pve-firewall
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
