#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
    configure)
	# Remove masks created by dh_systemd_enable on package removal.
	deb-systemd-helper unmask pve-firewall.service >/dev/null || true

	# modeled after dh_systemd_start output
	systemctl --system daemon-reload >/dev/null || true
	if [ -n "$2" ]; then
		_dh_action=try-reload-or-restart
	else
		_dh_action=start
	fi
	deb-systemd-invoke $_dh_action pve-firewall.service >/dev/null || true
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
