#!/bin/sh

set -e

case "$1" in
    configure)
    ;;

    triggered)
        invoke-rc.d pve-firewall restart
	exit 0
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0